
spring:
  datasource:
    username: matnen
    password: matnen
    url: jdbc:postgresql://localhost:5432/qw_dta_db
  liquibase.enabled: true
  liquibase.change-log: classpath:db/changelog/liquibase-changelog.xml

management:
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true


jwt:
  secret: quickwork
